import {
  pgTable,
  text,
  timestamp,
  boolean,
  varchar,
  uuid,
  integer,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/*
 * Crockford Base32
 * 0123456789ABCDEFGHJKMNPQRSTVWXYZ
 */
const base32Regex = "^[0-9A-HJKMNP-TV-Z]{6}$";

/* =====================================================
   BETTER-AUTH TABLES
===================================================== */

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/* =====================================================
   BOOKS (metadata)
===================================================== */

export const books = pgTable("books", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  author: text("author"),
  isbn: text("isbn"),
  publishedYear: integer("published_year"),
  description: text("description"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

/* =====================================================
   RACKS (physical location)
===================================================== */

export const racks = pgTable(
  "racks",
  {
    id: varchar("id", { length: 6 }).primaryKey(),
    room: text("room").notNull(),
    cupboard: text("cupboard"),
    rackNumber: text("rack_number"),
    description: text("description"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    base32Check: sql`CHECK (${table.id} ~ '${sql.raw(base32Regex)}')`,
  })
);

/* =====================================================
   BOOK COPIES (physical books)
===================================================== */

export const bookCopies = pgTable(
  "book_copies",
  {
    id: varchar("id", { length: 6 }).primaryKey(),
    bookId: uuid("book_id")
      .notNull()
      .references(() => books.id),
    rackId: varchar("rack_id", { length: 6 }).references(() => racks.id),
    state: text("state").notNull().default("available"),
    borrowedBy: text("borrowed_by").references(() => user.id),
    borrowedAt: timestamp("borrowed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    base32Check: sql`CHECK (${table.id} ~ '${sql.raw(base32Regex)}')`,
    rackCheck: sql`CHECK (${table.rackId} IS NULL OR ${table.rackId} ~ '${sql.raw(base32Regex)}')`,
    rackIndex: index("copies_rack_idx").on(table.rackId),
    bookIndex: index("copies_book_idx").on(table.bookId),
    borrowerIndex: index("copies_borrower_idx").on(table.borrowedBy),
  })
);

/* =====================================================
   QR LABELS (issued QR IDs — dedup ledger)
   
   Every ID generated by the batch QR endpoint is recorded
   here BEFORE the PDF is returned. This guarantees no two
   batches ever produce the same ID, even across restarts.
===================================================== */

export const qrLabels = pgTable(
  "qr_labels",
  {
    id: varchar("id", { length: 6 }).notNull(),
    type: text("type").notNull(), // "book" or "rack"
    batchId: uuid("batch_id").notNull(), // groups labels from one request
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    pk: sql`PRIMARY KEY (type, id)`,
    batchIndex: index("qr_labels_batch_idx").on(table.batchId),
    base32Check: sql`CHECK (${table.id} ~ '${sql.raw(base32Regex)}')`,
  })
);

/* =====================================================
   BORROWS (borrow history)
===================================================== */

export const borrows = pgTable(
  "borrows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    copyId: varchar("copy_id", { length: 6 })
      .notNull()
      .references(() => bookCopies.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    borrowedAt: timestamp("borrowed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    returnedAt: timestamp("returned_at", { withTimezone: true }),
  },
  (table) => ({
    copyIndex: index("borrows_copy_idx").on(table.copyId),
    userIndex: index("borrows_user_idx").on(table.userId),
    activeBorrowIndex: sql`CREATE UNIQUE INDEX IF NOT EXISTS active_borrow_per_copy ON borrows(copy_id) WHERE returned_at IS NULL`,
  })
);